"""initial schema: users, plaid, accounts, transactions, categories

Revision ID: 67f4dfcb98fe
Revises: 
Create Date: 2026-07-13 01:57:13.400672

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '67f4dfcb98fe'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_category_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_category_id'], ['categories.id'], name=op.f('fk_categories_parent_category_id_categories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('parent_category_id', 'name', name=op.f('uq_categories_parent_category_id'), postgresql_nulls_not_distinct=True)
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('plaid_items',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plaid_item_id', sa.String(length=255), nullable=False),
    sa.Column('institution_id', sa.String(length=255), nullable=True),
    sa.Column('institution_name', sa.String(length=255), nullable=True),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('active', 'login_required', 'error', 'disconnected', name='plaiditemstatus', native_enum=False, create_constraint=True, length=50), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_plaid_items_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plaid_items')),
    sa.UniqueConstraint('plaid_item_id', name=op.f('uq_plaid_items_plaid_item_id'))
    )
    op.create_index(op.f('ix_plaid_items_user_id'), 'plaid_items', ['user_id'], unique=False)
    op.create_table('accounts',
    sa.Column('plaid_item_id', sa.UUID(), nullable=False),
    sa.Column('plaid_account_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=False),
    sa.Column('account_subtype', sa.String(length=50), nullable=True),
    sa.Column('current_balance', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('available_balance', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'USD'"), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plaid_item_id'], ['plaid_items.id'], name=op.f('fk_accounts_plaid_item_id_plaid_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts')),
    sa.UniqueConstraint('plaid_account_id', name=op.f('uq_accounts_plaid_account_id'))
    )
    op.create_index(op.f('ix_accounts_plaid_item_id'), 'accounts', ['plaid_item_id'], unique=False)
    op.create_table('plaid_sync_state',
    sa.Column('plaid_item_id', sa.UUID(), nullable=False),
    sa.Column('cursor', sa.Text(), nullable=True),
    sa.Column('last_synced_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('sync_status', sa.Enum('idle', 'syncing', 'error', name='syncstatus', native_enum=False, create_constraint=True, length=50), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plaid_item_id'], ['plaid_items.id'], name=op.f('fk_plaid_sync_state_plaid_item_id_plaid_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plaid_sync_state')),
    sa.UniqueConstraint('plaid_item_id', name=op.f('uq_plaid_sync_state_plaid_item_id'))
    )
    op.create_table('raw_plaid_transactions',
    sa.Column('plaid_transaction_id', sa.String(length=255), nullable=False),
    sa.Column('plaid_item_id', sa.UUID(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('processing_status', sa.Enum('pending', 'processed', 'failed', 'skipped', name='processingstatus', native_enum=False, create_constraint=True, length=50), nullable=False),
    sa.Column('received_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['plaid_item_id'], ['plaid_items.id'], name=op.f('fk_raw_plaid_transactions_plaid_item_id_plaid_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raw_plaid_transactions')),
    sa.UniqueConstraint('plaid_transaction_id', name=op.f('uq_raw_plaid_transactions_plaid_transaction_id'))
    )
    op.create_index('ix_raw_plaid_transactions_pending', 'raw_plaid_transactions', ['received_at'], unique=False, postgresql_where=sa.text("processing_status = 'pending'"))
    op.create_index(op.f('ix_raw_plaid_transactions_plaid_item_id'), 'raw_plaid_transactions', ['plaid_item_id'], unique=False)
    op.create_table('transactions',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('plaid_transaction_id', sa.String(length=255), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('merchant_name', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'USD'"), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('transaction_type', sa.Enum('debit', 'credit', name='transactiontype', native_enum=False, create_constraint=True, length=50), nullable=False),
    sa.Column('pending', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_transactions_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_transactions_category_id_categories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions')),
    sa.UniqueConstraint('plaid_transaction_id', name=op.f('uq_transactions_plaid_transaction_id'))
    )
    op.create_index('ix_transactions_account_id_transaction_date', 'transactions', ['account_id', 'transaction_date'], unique=False, postgresql_using='btree', postgresql_ops={'transaction_date': 'DESC'})
    op.create_index(op.f('ix_transactions_category_id'), 'transactions', ['category_id'], unique=False)
    op.create_index(op.f('ix_transactions_merchant_name'), 'transactions', ['merchant_name'], unique=False)
    op.create_index('ix_transactions_transaction_date', 'transactions', ['transaction_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_transaction_date', table_name='transactions')
    op.drop_index(op.f('ix_transactions_merchant_name'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_category_id'), table_name='transactions')
    op.drop_index('ix_transactions_account_id_transaction_date', table_name='transactions', postgresql_using='btree', postgresql_ops={'transaction_date': 'DESC'})
    op.drop_table('transactions')
    op.drop_index(op.f('ix_raw_plaid_transactions_plaid_item_id'), table_name='raw_plaid_transactions')
    op.drop_index('ix_raw_plaid_transactions_pending', table_name='raw_plaid_transactions', postgresql_where=sa.text("processing_status = 'pending'"))
    op.drop_table('raw_plaid_transactions')
    op.drop_table('plaid_sync_state')
    op.drop_index(op.f('ix_accounts_plaid_item_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_plaid_items_user_id'), table_name='plaid_items')
    op.drop_table('plaid_items')
    op.drop_table('users')
    op.drop_table('categories')
    # ### end Alembic commands ###
