"""add transaction classification column

Revision ID: 9e06cc91d068
Revises: 0c1d48686859
Create Date: 2026-07-14 00:05:01.436504

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '9e06cc91d068'
down_revision: str | None = '0c1d48686859'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('classification', sa.Enum('income', 'expense', 'transfer', 'fee', 'refund', 'unknown', name='transactionclassification', native_enum=False, create_constraint=True, length=50), server_default=sa.text("'unknown'"), nullable=False))
    # NOTE: autogenerate's false drop/create of
    # ix_transactions_account_id_transaction_date (DESC not reflected)
    # removed by hand — the existing index is correct.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'classification')
    # ### end Alembic commands ###
