"""add user password_hash

Revision ID: 5a5c2c8f55ab
Revises: 9e06cc91d068
Create Date: 2026-07-14 01:53:54.361664

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '5a5c2c8f55ab'
down_revision: str | None = '9e06cc91d068'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # (autogenerate's false DESC-index drop/create removed by hand)
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
